# docker-compose.yml
version: '3'
services:
  app:
    build: .
    working_dir: /mnt
    volumes:
      - .:/mnt
    environment:
      PYTHONPATH: .
      PYTHONUSERBASE: /mnt/vendor
    command: python main.py